-- GENERATE XSR.CFG_PROPERTIES SQL
SELECT 'INSERT INTO XSR.CFG_PROPERTIES(PROPERTIES_ID,KEY,VALUE) ' CONCAT
X'0A' CONCAT
'   ' CONCAT
'VALUES (NEXTVAL FOR XSR.SEQ_PROPERTIES_ID,''' CONCAT
RTRIM(key) CONCAT
''',''' CONCAT
RTRIM(value) CONCAT
''')' CONCAT
X'3B'
FROM xsr.cfg_properties
ORDER BY key,value;

