


---------------------------------
-- for existing granted privileges, excluding the original definer of the object
---------------------------------


CREATE SEQUENCE "XSR     "."SEQ_ADMIN_RIGHTS_ID" AS INTEGER
	MINVALUE 2000000 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 50 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_APP_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ATCH_MNT_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 50 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_AUDIT_ACTION_TYPE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	NO CACHE NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_AUDIT_LOG_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	NO CACHE NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_AUDIT_OBJ_TYPE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	NO CACHE NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_A_ROUTE_EXCL_DAY_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_A_ROUTE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_A_ROUTE_KEYWORD_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_A_ROUTE_KEYWORD_LIST_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_A_ROUTE_SET_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_A_ROUTE_TIME_SLOT_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_BASIC_ROUTE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_COMP_GROUP_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_COMP_GROUP_TYPE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ERR_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_FAMS_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_FAMS_MESSAGE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_FAMS_NODE_ID" AS SMALLINT
	MINVALUE 1 MAXVALUE 32767
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_FAMS_STATUS_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	NO CACHE NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_OBJ_TYPE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_OS_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_PMR_TEXT_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_PREM_ROUTE_EXCL_DAYS_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_PREM_ROUTE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_PREM_ROUTE_SET_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_PREM_ROUTE_TIME_SLOT_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_PROPERTIES_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_QUEUE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 3
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_COUNTRY_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_ENT_EXC_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_EXCL_DAY_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_KEYWORD_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_KEYWORD_LIST_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_LOG_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_SET_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_ROUTE_TIME_SLOT_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_SCOPE_TYPE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_SYNC_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_TRAN_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_T_ROUTE_EXCL_DAY_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_T_ROUTE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_T_ROUTE_KEYWORD_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_T_ROUTE_KEYWORD_LIST_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_T_ROUTE_SET_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_T_ROUTE_TIME_SLOT_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;
CREATE SEQUENCE "XSR     "."SEQ_USER_PROFILE_ID" AS INTEGER
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;



COMMIT WORK;

