
-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DFTRTN_INS
   NO CASCADE BEFORE  INSERT  ON XSR.PMR_DRAFT_RETAIN_INFO
   REFERENCING  NEW AS N  FOR EACH ROW  MODE DB2SQL
BEGIN ATOMIC
        SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
        SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
        SET N.UPDATE_USER=N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
      SET N.CREATE_USER = USER;--
      SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DFTRTN_UPD
   NO CASCADE BEFORE  UPDATE  ON XSR.PMR_DRAFT_RETAIN_INFO
   REFERENCING  OLD AS O  NEW AS N  FOR EACH ROW  MODE DB2SQL
BEGIN ATOMIC
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') then
     SET N.UPDATE_USER = USER;--
   END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DFTXSR_DLT_LOG
   AFTER  DELETE  ON XSR.PMR_DRAFT_XSR_INFO
   REFERENCING  OLD AS O  FOR EACH ROW  MODE DB2SQL
   INSERT INTO XSR.PMR_DRAFT_XSR_INFO_LOG
(
SRC_TRAN_ID,
SRC_APPL,
SRC_NODE,
SUPPORT_ID,
TITLE,
DESCRIPTION,
CONTACT_METHOD,
ALT_CONTACT_METHOD,
ALT_CONTACT_ID,
OPERSYS_ID,
CUST_TRACKING_NUM,
OTHER_COMP_DSCR,
INITIAL_SEVERITY,
SEVERITY_DESCRIPTION,
LOCALE,
OPEN_COUNT,
PMR_CREATE_SRC_APPL,
CREATE_CONTACT_ID,
UPDATE_CONTACT_ID,
ADD_ALT_CONTACT_ID,
REMOVE_ALT_CONTACT_ID,
PARTNER_INIT,
SUBMIT_TYPE,
CONTACT_ID,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
O.SRC_TRAN_ID,
O.SRC_APPL,
O.SRC_NODE,
O.SUPPORT_ID,
O.TITLE,
O.DESCRIPTION,
O.CONTACT_METHOD,
O.ALT_CONTACT_METHOD,
O.ALT_CONTACT_ID,
O.OPERSYS_ID,
O.CUST_TRACKING_NUM,
O.OTHER_COMP_DSCR,
O.INITIAL_SEVERITY,
O.SEVERITY_DESCRIPTION,
O.LOCALE,
O.OPEN_COUNT,
O.PMR_CREATE_SRC_APPL,
O.CREATE_CONTACT_ID,
O.UPDATE_CONTACT_ID,
O.ADD_ALT_CONTACT_ID,
O.REMOVE_ALT_CONTACT_ID,
O.PARTNER_INIT,
O.SUBMIT_TYPE,
O.CONTACT_ID,
O.CREATE_USER,
O.CREATE_DATETIME,
O.UPDATE_USER,
CURRENT TIMESTAMP,
'D'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DFTXSR_INS_LOG AFTER  INSERT  ON XSR.PMR_DRAFT_XSR_INFO
 REFERENCING  NEW AS N  FOR EACH ROW  MODE DB2SQL INSERT INTO XSR.PMR_DRAFT_XSR_INFO_LOG
(
SRC_TRAN_ID,
SRC_APPL,
SRC_NODE,
SUPPORT_ID,
TITLE,
DESCRIPTION,
CONTACT_METHOD,
ALT_CONTACT_METHOD,
ALT_CONTACT_ID,
OPERSYS_ID,
CUST_TRACKING_NUM,
OTHER_COMP_DSCR,
INITIAL_SEVERITY,
SEVERITY_DESCRIPTION,
LOCALE,
OPEN_COUNT,
PMR_CREATE_SRC_APPL,
CREATE_CONTACT_ID,
UPDATE_CONTACT_ID,
ADD_ALT_CONTACT_ID,
REMOVE_ALT_CONTACT_ID,
PARTNER_INIT,
SUBMIT_TYPE,
CONTACT_ID,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
N.SRC_TRAN_ID,
N.SRC_APPL,
N.SRC_NODE,
N.SUPPORT_ID,
N.TITLE,
N.DESCRIPTION,
N.CONTACT_METHOD,
N.ALT_CONTACT_METHOD,
N.ALT_CONTACT_ID,
N.OPERSYS_ID,
N.CUST_TRACKING_NUM,
N.OTHER_COMP_DSCR,
N.INITIAL_SEVERITY,
N.SEVERITY_DESCRIPTION,
N.LOCALE,
N.OPEN_COUNT,
N.PMR_CREATE_SRC_APPL,
N.CREATE_CONTACT_ID,
N.UPDATE_CONTACT_ID,
N.ADD_ALT_CONTACT_ID,
N.REMOVE_ALT_CONTACT_ID,
N.PARTNER_INIT,
N.SUBMIT_TYPE,
N.CONTACT_ID,
N.CREATE_USER,
N.CREATE_DATETIME,
N.UPDATE_USER,
N.UPDATE_DATETIME,
'I'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DFTXSR_UPD_LOG
   AFTER  UPDATE  ON XSR.PMR_DRAFT_XSR_INFO
   REFERENCING  OLD AS O  NEW AS N  FOR EACH ROW  MODE DB2SQL
   INSERT INTO XSR.PMR_DRAFT_XSR_INFO_LOG
(
SRC_TRAN_ID,
SRC_APPL,
SRC_NODE,
SUPPORT_ID,
TITLE,
DESCRIPTION,
CONTACT_METHOD,
ALT_CONTACT_METHOD,
ALT_CONTACT_ID,
OPERSYS_ID,
CUST_TRACKING_NUM,
OTHER_COMP_DSCR,
INITIAL_SEVERITY,
SEVERITY_DESCRIPTION,
LOCALE,
OPEN_COUNT,
PMR_CREATE_SRC_APPL,
CREATE_CONTACT_ID,
UPDATE_CONTACT_ID,
ADD_ALT_CONTACT_ID,
REMOVE_ALT_CONTACT_ID,
PARTNER_INIT,
SUBMIT_TYPE,
CONTACT_ID,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
N.SRC_TRAN_ID,
N.SRC_APPL,
N.SRC_NODE,
N.SUPPORT_ID,
N.TITLE,
N.DESCRIPTION,
N.CONTACT_METHOD,
N.ALT_CONTACT_METHOD,
N.ALT_CONTACT_ID,
N.OPERSYS_ID,
N.CUST_TRACKING_NUM,
N.OTHER_COMP_DSCR,
N.INITIAL_SEVERITY,
N.SEVERITY_DESCRIPTION,
N.LOCALE,
N.OPEN_COUNT,
N.PMR_CREATE_SRC_APPL,
N.CREATE_CONTACT_ID,
N.UPDATE_CONTACT_ID,
N.ADD_ALT_CONTACT_ID,
N.REMOVE_ALT_CONTACT_ID,
N.PARTNER_INIT,
N.SUBMIT_TYPE,
N.CONTACT_ID,
O.CREATE_USER,
O.CREATE_DATETIME,
N.UPDATE_USER,
N.UPDATE_DATETIME,
'U'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DRAFT_DLT_LOG AFTER DELETE ON XSR.PMR_DRAFT REFERENCING
OLD AS O FOR EACH ROW MODE DB2SQL INSERT INTO XSR.PMR_DRAFT_LOG
(
SRC_TRAN_ID,
SRC_APPL,
SRC_NODE,
PMR_NUM,
BRANCH,
RETAIN_CNTRY_CODE,
STATE,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
O.SRC_TRAN_ID,
O.SRC_APPL,
O.SRC_NODE,
O.PMR_NUM,
O.BRANCH,
O.RETAIN_CNTRY_CODE,
O.STATE,
O.CREATE_USER,
O.CREATE_DATETIME,
O.UPDATE_USER,
CURRENT TIMESTAMP,
'D'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DRAFT_INS
   NO CASCADE BEFORE  INSERT  ON XSR.PMR_DRAFT  REFERENCING  NEW AS N
   FOR EACH ROW  MODE DB2SQL BEGIN ATOMIC
      SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
      SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
      SET N.UPDATE_USER=N.CREATE_USER;--
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
      SET N.CREATE_USER = USER;--
      SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DRAFT_INS_LOG AFTER  INSERT  ON XSR.PMR_DRAFT  REFERENCING
 NEW AS N  FOR EACH ROW  MODE DB2SQL INSERT INTO XSR.PMR_DRAFT_LOG
(
SRC_TRAN_ID,
SRC_APPL,
SRC_NODE,
PMR_NUM,
BRANCH,
RETAIN_CNTRY_CODE,
STATE,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
N.SRC_TRAN_ID,
N.SRC_APPL,
N.SRC_NODE,
N.PMR_NUM,
N.BRANCH,
N.RETAIN_CNTRY_CODE,
N.STATE,
N.CREATE_USER,
N.CREATE_DATETIME,
N.UPDATE_USER,
N.UPDATE_DATETIME,
'I'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DRAFT_UPD NO CASCADE BEFORE  UPDATE  ON XSR.PMR_DRAFT
 REFERENCING  OLD AS O  NEW AS N  FOR EACH ROW  MODE DB2SQL BEGIN ATOMIC
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') then
     SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.PMR_DRAFT_UPD_LOG AFTER  UPDATE  ON XSR.PMR_DRAFT  REFERENCING
 OLD AS O  NEW AS N  FOR EACH ROW  MODE DB2SQL INSERT INTO XSR.PMR_DRAFT_LOG
(
SRC_TRAN_ID,
SRC_APPL,
SRC_NODE,
PMR_NUM,
BRANCH,
RETAIN_CNTRY_CODE,
STATE,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
N.SRC_TRAN_ID,
N.SRC_APPL,
N.SRC_NODE,
N.PMR_NUM,
N.BRANCH,
N.RETAIN_CNTRY_CODE,
N.STATE,
O.CREATE_USER,
O.CREATE_DATETIME,
N.UPDATE_USER,
N.UPDATE_DATETIME,
'U'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TDA_RIGHT_OBJ_LOG AFTER  DELETE  ON XSR.RIGHT_OBJ  REFERENCING
 OLD AS O  FOR EACH ROW  MODE DB2SQL   INSERT INTO XSR.RIGHT_OBJ_LOG
(
  USER_ID,
  OBJ_TYPE_ID,
  OBJ_ID,
  CREATE_USER,
  CREATE_DATETIME,
  UPDATE_USER,
  UPDATE_DATETIME,
  ACTION_FLAG
)
VALUES
(
  O.USER_ID,
  O.OBJ_TYPE_ID,
  O.OBJ_ID,
  O.CREATE_USER,
  O.CREATE_DATETIME,
  O.UPDATE_USER,
  CURRENT TIMESTAMP,
  'D'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIA_RIGHT_OBJ_LOG AFTER  INSERT  ON XSR.RIGHT_OBJ  REFERENCING
 NEW AS N  FOR EACH ROW  MODE DB2SQL
  INSERT INTO XSR.RIGHT_OBJ_LOG
(
  USER_ID,
  OBJ_TYPE_ID,
  OBJ_ID,
  CREATE_USER,
  CREATE_DATETIME,
  UPDATE_USER,
  UPDATE_DATETIME,
  ACTION_FLAG
)
VALUES
(
  N.USER_ID,
  N.OBJ_TYPE_ID,
  N.OBJ_ID,
  N.CREATE_USER,
  N.CREATE_DATETIME,
  N.UPDATE_USER,
  N.UPDATE_DATETIME,
  'I'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_ADMIN_AUTH
   NO CASCADE BEFORE INSERT ON XSR.ADMIN_AUTH
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
set n.update_user = n.create_user;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_ADMIN_RIGHTS
   NO CASCADE BEFORE INSERT ON XSR.ADMIN_RIGHTS
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
set n.update_user = n.create_user;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_AUDIT_LOG
NO CASCADE BEFORE INSERT ON XSR.AUDIT_LOG
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.TIME_STAMP = CURRENT TIMESTAMP;--
IF (N.USER_ID IS NULL OR RTRIM(N.USER_ID) = '') THEN
SET N.USER_ID = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_AVL_OS
NO CASCADE BEFORE INSERT ON XSR.AVL_OPERATING_SYSTEM
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_BP_PDR
   NO CASCADE BEFORE INSERT ON XSR.BP_SITE_PMR_DRAFT_XREF
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_BP_PRX
   NO CASCADE BEFORE INSERT ON XSR.BP_SITE_PMR_RETRY_XREF
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_BP_PX
   NO CASCADE BEFORE INSERT ON XSR.BP_SITE_PMR_XREF
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_CMP_GRP
NO CASCADE BEFORE INSERT ON XSR.COMP_GROUP
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_CMP_GRP_CMP_X
NO CASCADE BEFORE UPDATE ON XSR.COMP_GROUP_COMP_XREF
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_CMP_GRP_X
NO CASCADE BEFORE INSERT ON XSR.COMP_GROUP_XREF
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_FAMS
NO CASCADE BEFORE INSERT ON XSR.FAMS
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_FAMS_CFG
NO CASCADE BEFORE INSERT ON XSR.FAMS_CONFIG
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_MSG_SUBST
NO CASCADE BEFORE INSERT ON XSR.MSG_SUBST
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_MSG_TMPL
NO CASCADE BEFORE INSERT ON XSR.MSG_TMPL
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_MSG_TOKEN
NO CASCADE BEFORE INSERT ON XSR.MSG_TOKEN
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_NTF_EREG
   NO CASCADE BEFORE INSERT ON XSR.NOTIFY_EVENT_REGISTRATION
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_USER = N.CREATE_USER;--
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
 SET N.CREATE_USER = USER;--
 SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_NTF_ET
   NO CASCADE BEFORE INSERT ON XSR.NOTIFY_EVENT_TRAN
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
 SET N.CREATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_NTF_ETRAN_ARCH
   NO CASCADE BEFORE INSERT ON XSR.NOTIFY_EVENT_TRAN_ARCHIVE
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.ARCHIVE_DATETIME = CURRENT TIMESTAMP;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_NTF_ETYPE
   NO CASCADE BEFORE INSERT ON XSR.NOTIFY_EVENT_TYPE
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_USER = N.CREATE_USER;--
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
 SET N.CREATE_USER = USER;--
 SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_NTF_ETYPE_AX
   NO CASCADE BEFORE INSERT ON XSR.NOTIFY_EVENT_TYPE_ACTION_XREF
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_USER = N.CREATE_USER;--
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
 SET N.CREATE_USER = USER;--
 SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_NTF_EUSER_TR
   NO CASCADE BEFORE INSERT ON XSR.NOTIFY_EVENT_USER_TRAN
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_USER = N.CREATE_USER;--
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
 SET N.CREATE_USER = USER;--
 SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_NTF_TRAN
   NO CASCADE BEFORE INSERT ON XSR.NOTIFY_TRAN
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_PMR_ATCHMT
NO CASCADE BEFORE INSERT ON XSR.PMR_ATTACHMENT
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_DRAFT
   NO CASCADE BEFORE INSERT ON XSR.PMR_DRAFT
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_DRFT_XI
   NO CASCADE BEFORE  INSERT  ON XSR.PMR_DRAFT_XSR_INFO
   REFERENCING  NEW AS N
   FOR EACH ROW  MODE DB2SQL
BEGIN ATOMIC
        SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
        SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
        SET N.UPDATE_USER=N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
      SET N.CREATE_USER = USER;--
      SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_PMR_ERR_TRN
NO CASCADE BEFORE INSERT ON XSR.PMR_ERR_TRAN
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_HDR
   NO CASCADE BEFORE INSERT ON XSR.PMR_HEADER
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_HDR_RTN_IN
   NO CASCADE BEFORE INSERT ON XSR.PMR_RETAIN_INFO
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_HDR_SIG_LN
   NO CASCADE BEFORE INSERT ON XSR.PMR_SIG_LINES
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_HDR_XSR_IN
   NO CASCADE BEFORE INSERT ON XSR.PMR_XSR_INFO
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_LOG
   NO CASCADE BEFORE INSERT ON XSR.PMR_LOG
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_RETRY
   NO CASCADE BEFORE INSERT ON XSR.PMR_RETRY
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_RETRY_RI
   NO CASCADE BEFORE INSERT ON XSR.PMR_RETRY_RETAIN_INFO
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_RETRY_XI
   NO CASCADE BEFORE INSERT ON XSR.PMR_RETRY_XSR_INFO
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_PMR_ROUTE_LG
NO CASCADE BEFORE INSERT ON XSR.PMR_ROUTE_LOG
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_PMR_TEXT
   NO CASCADE BEFORE INSERT ON XSR.PMR_TEXT
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_RETAIN_ACT_LG
NO CASCADE BEFORE INSERT ON XSR.RETAIN_ACT_LOG
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_RETAIN_CC
NO CASCADE BEFORE INSERT ON XSR.RETAIN_CNTRY_CODE
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_RETAIN_ERR_LG
NO CASCADE BEFORE INSERT ON XSR.RETAIN_ERR_LOG
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_RIGHT_OBJ
NO CASCADE BEFORE INSERT ON XSR.RIGHT_OBJ
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_RIGHT_OBJ_TRN
NO CASCADE BEFORE INSERT ON XSR.RIGHT_OBJ_TRAN
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_RIGHT_OBJ_TYP
NO CASCADE BEFORE INSERT ON XSR.RIGHT_OBJ_TYPE
REFERENCING  NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_TZ
   NO CASCADE BEFORE INSERT ON XSR.TIME_ZONE
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_USER_AUTH
   NO CASCADE BEFORE INSERT ON XSR.USER_AUTH
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_USER_AUTH_LOG
   NO CASCADE BEFORE INSERT ON XSR.USER_AUTH_LOG
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_USER_LE_LOG
   NO CASCADE BEFORE INSERT ON XSR.USER_LOGIN_ERR_LOG
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_USER_LX_LG
   NO CASCADE BEFORE INSERT ON XSR.USER_LOGIN_XREF_LOG
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_USER_PROFILE
   NO CASCADE BEFORE INSERT ON XSR.USER_PROFILE
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN

      SET N.CREATE_USER = USER;  --
      SET N.UPDATE_USER = USER;  --
   END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_USR_PMR_DRF_X
   NO CASCADE BEFORE INSERT ON XSR.USER_PMR_DRAFT_XREF
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_USR_PMR_RTY_X
   NO CASCADE BEFORE INSERT ON XSR.USER_PMR_RETRY_XREF
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_USR_PMR_XREF
   NO CASCADE BEFORE INSERT ON XSR.USER_PMR_XREF
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_USR_PRD_FAV
   NO CASCADE BEFORE INSERT ON XSR.USER_PROD_FAVORITES
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TIB_USR_PROF_NTF
   NO CASCADE BEFORE INSERT ON XSR.USER_PROFILE_NOTIFICATION
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
SET N.UPDATE_USER = N.CREATE_USER;  --
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;  --
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TIB_USR_PROF_RPT
   NO CASCADE BEFORE INSERT ON XSR.USER_PROFILE_REPORT
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUA_RIGHT_OBJ_LOG AFTER  UPDATE  ON XSR.RIGHT_OBJ  REFERENCING
 OLD AS O  NEW AS N  FOR EACH ROW  MODE DB2SQL
  INSERT INTO XSR.RIGHT_OBJ_LOG
(
  USER_ID,
  OBJ_TYPE_ID,
  OBJ_ID,
  CREATE_USER,
  CREATE_DATETIME,
  UPDATE_USER,
  UPDATE_DATETIME,
  ACTION_FLAG
)
VALUES
(
  N.USER_ID,
  N.OBJ_TYPE_ID,
  N.OBJ_ID,
  O.CREATE_USER,
  O.CREATE_DATETIME,
  N.UPDATE_USER,
  N.UPDATE_DATETIME,
  'U'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB1_USER_PROFILE
   NO CASCADE BEFORE UPDATE ON XSR.USER_PROFILE
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
   IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
     SET N.UPDATE_USER = USER;  --
   END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB2_USER_PROFILE NO CASCADE BEFORE UPDATE OF AUP_ACCEPTED_FLAG
ON XSR.USER_PROFILE REFERENCING NEW AS N FOR EACH ROW
BEGIN ATOMIC
    SET N.AUP_ACCEPTED_DATE =
    CASE
    WHEN N.AUP_ACCEPTED_FLAG = 1
        THEN CURRENT DATE
    WHEN N.AUP_ACCEPTED_FLAG = 0
        THEN NULL
    END;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
drop trigger xsr.t_ub_appl_auth;
create trigger xsr.t_ub_appl_auth no cascade
before update on xsr.appl_auth
referencing new as n for each row mode db2sql
begin atomic
   set n.update_datetime = current timestamp;--
   if (n.update_user is null or rtrim(n.update_user) = '') then
     set n.update_user = user;--
   end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
drop trigger xsr.t_ib_appl_auth;
create trigger xsr.t_ib_appl_auth
before insert on xsr.appl_auth
referencing new as n for each row mode db2sql
begin atomic
   set n.create_datetime = current timestamp;--
   set n.update_datetime = current timestamp;--
   if (n.create_user is null or rtrim(n.create_user) = '') then

      set n.create_user = user;--
      set n.update_user = user;--
   end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_ADMIN_AUTH
   NO CASCADE BEFORE UPDATE ON XSR.ADMIN_AUTH
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_ADMIN_RIGHTS
   NO CASCADE BEFORE UPDATE ON XSR.ADMIN_RIGHTS
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_AUDIT_LOG
NO CASCADE BEFORE UPDATE ON XSR.AUDIT_LOG
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.TIME_STAMP = CURRENT TIMESTAMP;--
IF (N.USER_ID IS NULL OR RTRIM(N.USER_ID) = '') THEN
SET N.USER_ID = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_AVL_OS
NO CASCADE BEFORE UPDATE ON XSR.AVL_OPERATING_SYSTEM
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_BP_PDR
   NO CASCADE BEFORE UPDATE ON XSR.BP_SITE_PMR_DRAFT_XREF
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_BP_PRX
   NO CASCADE BEFORE UPDATE ON XSR.BP_SITE_PMR_RETRY_XREF
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_BP_PX
   NO CASCADE BEFORE UPDATE ON XSR.BP_SITE_PMR_XREF
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_CMP_GRP
NO CASCADE BEFORE UPDATE ON XSR.COMP_GROUP
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_FAMS
NO CASCADE BEFORE UPDATE ON XSR.FAMS
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_FAMS_CFG
NO CASCADE BEFORE UPDATE ON XSR.FAMS_CONFIG
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_MSG_TMPL
NO CASCADE BEFORE UPDATE ON XSR.MSG_TMPL
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_MSG_TOKEN
NO CASCADE BEFORE UPDATE ON XSR.MSG_TOKEN
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_NTF_EREG
   NO CASCADE BEFORE UPDATE ON XSR.NOTIFY_EVENT_REGISTRATION
   REFERENCING NEW AS N OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_NTF_ET
   NO CASCADE BEFORE UPDATE ON XSR.NOTIFY_EVENT_TRAN
   REFERENCING NEW AS N OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
 SET N.CREATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_NTF_ETYPE
   NO CASCADE BEFORE UPDATE ON XSR.NOTIFY_EVENT_TYPE
   REFERENCING NEW AS N OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_NTF_EUSER_TR
   NO CASCADE BEFORE UPDATE ON XSR.NOTIFY_EVENT_USER_TRAN
   REFERENCING NEW AS N OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
   END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_NTF_TRAN
   NO CASCADE BEFORE UPDATE ON XSR.NOTIFY_TRAN
   REFERENCING  NEW AS N
 OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_PMR_ATCHMT
NO CASCADE BEFORE UPDATE ON XSR.PMR_ATTACHMENT
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_DRAFT
   NO CASCADE BEFORE UPDATE ON XSR.PMR_DRAFT
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_DRFT_XI
   NO CASCADE BEFORE  UPDATE  ON XSR.PMR_DRAFT_XSR_INFO
   REFERENCING  OLD AS O  NEW AS N  FOR EACH ROW  MODE DB2SQL
BEGIN ATOMIC
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') then
     SET N.UPDATE_USER = USER;--
   END IF;  --
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_PMR_ERR_TRN
NO CASCADE BEFORE UPDATE ON XSR.PMR_ERR_TRAN
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_HDR
   NO CASCADE BEFORE UPDATE ON XSR.PMR_HEADER
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_HDR_RTN_IN
   NO CASCADE BEFORE UPDATE ON XSR.PMR_RETAIN_INFO
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_HDR_SIG_LN
   NO CASCADE BEFORE UPDATE ON XSR.PMR_SIG_LINES
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_HDR_XSR_IN
   NO CASCADE BEFORE UPDATE ON XSR.PMR_XSR_INFO
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_LOG
   NO CASCADE BEFORE UPDATE ON XSR.PMR_LOG
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_RETRY
   NO CASCADE BEFORE UPDATE ON XSR.PMR_RETRY
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_RETRY_RI
   NO CASCADE BEFORE UPDATE ON XSR.PMR_RETRY_RETAIN_INFO
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_RETRY_XI
   NO CASCADE BEFORE UPDATE ON XSR.PMR_RETRY_XSR_INFO
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_PMR_ROUTE_LG
NO CASCADE BEFORE UPDATE ON XSR.PMR_ROUTE_LOG
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_PMR_TEXT
   NO CASCADE BEFORE UPDATE ON XSR.PMR_TEXT
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_RETAIN_ACT_LG
NO CASCADE BEFORE UPDATE ON XSR.RETAIN_ACT_LOG
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_RETAIN_CC
NO CASCADE BEFORE UPDATE ON XSR.RETAIN_CNTRY_CODE
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_RETAIN_ERR_LG
NO CASCADE BEFORE UPDATE ON XSR.RETAIN_ERR_LOG
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_RIGHT_OBJ
NO CASCADE BEFORE UPDATE ON XSR.RIGHT_OBJ
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_RIGHT_OBJ_TRN
NO CASCADE BEFORE UPDATE ON XSR.RIGHT_OBJ_TRAN
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_RIGHT_OBJ_TYP
NO CASCADE BEFORE UPDATE ON XSR.RIGHT_OBJ_TYPE
REFERENCING NEW AS N OLD AS O
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_TZ
   NO CASCADE BEFORE UPDATE ON XSR.TIME_ZONE
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_USER_AUTH
   NO CASCADE BEFORE UPDATE ON XSR.USER_AUTH
   REFERENCING  NEW AS N
 OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_USER_AUTH_LOG
   NO CASCADE BEFORE UPDATE ON XSR.USER_AUTH_LOG
   REFERENCING  NEW AS N
 OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_USER_LE_LOG
   NO CASCADE BEFORE UPDATE ON XSR.USER_LOGIN_ERR_LOG
   REFERENCING  NEW AS N
 OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_USER_LX_LG
   NO CASCADE BEFORE UPDATE ON XSR.USER_LOGIN_XREF_LOG
   REFERENCING  NEW AS N
 OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_USR_PMR_DRF_X
   NO CASCADE BEFORE UPDATE ON XSR.USER_PMR_DRAFT_XREF
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_USR_PMR_RTY_X
   NO CASCADE BEFORE UPDATE ON XSR.USER_PMR_RETRY_XREF
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_USR_PMR_XREF
   NO CASCADE BEFORE UPDATE ON XSR.USER_PMR_XREF
   REFERENCING  NEW AS N
      OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_USR_PRD_FAV
   NO CASCADE BEFORE UPDATE ON XSR.USER_PROD_FAVORITES
   REFERENCING  NEW AS N
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.TUB_USR_PROF_NTF
   NO CASCADE BEFORE UPDATE ON XSR.USER_PROFILE_NOTIFICATION
   REFERENCING  NEW AS N
 OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;  --
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;  --
END IF;  --
END
;

SET CURRENT SCHEMA = "XSR     ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRPROD";
CREATE TRIGGER XSR.TUB_USR_PROF_RPT
   NO CASCADE BEFORE UPDATE ON XSR.USER_PROFILE_REPORT
   REFERENCING  NEW AS N
 OLD AS O
   FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_DA_MSG_LOG AFTER DELETE ON XSR.MSG_OUTBOUND  REFERENCING
 OLD AS O  FOR EACH ROW  MODE DB2SQL
INSERT INTO XSR.MSG_LOG
(
  TRAN_ID,
  MSG_TMPL_ID,
  LOCALE,
  SRC_APPL,
  TO,
  FROM,
  CC,
  BCC,
  SUBJECT,
  REASON,
  PMR_NUM,
  BRANCH ,
  RETAIN_CNTRY_CODE,
  PMR_TEXT_IDS,
  SHORT_DESCRIPTION,
  CREATE_USER,
  CREATE_DATETIME,
  UPDATE_USER,
  UPDATE_DATETIME,
  CONTACT_ID,
  CUST_NAME,
  SRC_SUPPORT_ID,
  CALLER_TYPE_DESCRIPTION,
  CALLER_STAT_DESCRIPTION,
  STC_QUES_TXT,
  FIRST_NAME,
  LAST_NAME,
  EMAIL_ADR,
  IBM_CUST_NUM,
  ENCRYPT_STRING,
  PSTC_EMAIL_ADR,
  NOMINATION_CONTACT_ID,
  SUBJECTLINE,
  SRC_NODE,
  SRC_TRAN_ID,
  BP_FIRST_NAME,
  BP_LAST_NAME,
  BP_CITY,
  BP_COMPANY_NAME,
  ACTION_FLAG
)
VALUES
(
O.TRAN_ID,
O.MSG_TMPL_ID,
O.LOCALE,
O.SRC_APPL,
O.TO,
O.FROM,
O.CC,
O.BCC,
O.SUBJECT,
O.REASON,
O.PMR_NUM,
O.BRANCH ,
O.RETAIN_CNTRY_CODE,
O.PMR_TEXT_IDS,
O.SHORT_DESCRIPTION,
O.CREATE_USER,
O.CREATE_DATETIME,
O.UPDATE_USER,
CURRENT TIMESTAMP,
O.CONTACT_ID,
O.CUST_NAME,
O.SRC_SUPPORT_ID,
O.CALLER_TYPE_DESCRIPTION,
O.CALLER_STAT_DESCRIPTION,
O.STC_QUES_TXT,
O.FIRST_NAME,
O.LAST_NAME,
O.EMAIL_ADR,
O.IBM_CUST_NUM,
O.ENCRYPT_STRING,
O.PSTC_EMAIL_ADR,
O.NOMINATION_CONTACT_ID,
O.SUBJECTLINE,
O.SRC_NODE,
O.SRC_TRAN_ID,
O.BP_FIRST_NAME,
O.BP_LAST_NAME,
O.BP_CITY,
O.BP_COMPANY_NAME,
'D'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_DA_USER_AUTH_LOG AFTER  DELETE  ON XSR.USER_AUTH  REFERENCING
 OLD AS O  FOR EACH ROW  MODE DB2SQL
INSERT INTO XSR.USER_AUTH_LOG
(
USER_ID,
RIGHT_MASK,
IS_LOCKED,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
O.USER_ID,
O.RIGHT_MASK,
O.IS_LOCKED,
O.CREATE_USER,
O.CREATE_DATETIME,
O.UPDATE_USER,
CURRENT TIMESTAMP,
'D'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_IA_MSG_LOG
   AFTER  INSERT  ON XSR.MSG_OUTBOUND
   REFERENCING  NEW AS N  FOR EACH ROW  MODE DB2SQL
INSERT INTO XSR.MSG_LOG
(
  TRAN_ID,
  MSG_TMPL_ID,
  LOCALE,
  SRC_APPL,
  TO,
  FROM,
  CC,
  BCC,
  SUBJECT,
  REASON,
  PMR_NUM,
  BRANCH ,
  RETAIN_CNTRY_CODE,
  PMR_TEXT_IDS,
  SHORT_DESCRIPTION,
  CREATE_USER,
  CREATE_DATETIME,
  UPDATE_USER,
  UPDATE_DATETIME,
  CONTACT_ID,
  CUST_NAME,
  SRC_SUPPORT_ID,
  CALLER_TYPE_DESCRIPTION,
  CALLER_STAT_DESCRIPTION,
  STC_QUES_TXT,
  FIRST_NAME,
  LAST_NAME,
  EMAIL_ADR,
  IBM_CUST_NUM,
  ENCRYPT_STRING,
  PSTC_EMAIL_ADR,
  NOMINATION_CONTACT_ID,
  SUBJECTLINE,
  SRC_NODE,
  SRC_TRAN_ID,
  BP_FIRST_NAME,
  BP_LAST_NAME,
  BP_CITY,
  BP_COMPANY_NAME,
  ACTION_FLAG
)
VALUES
(
N.TRAN_ID,
N.MSG_TMPL_ID,
N.LOCALE,
N.SRC_APPL,
N.TO,
N.FROM,
N.CC,
N.BCC,
N.SUBJECT,
N.REASON,
N.PMR_NUM,
N.BRANCH ,
N.RETAIN_CNTRY_CODE,
N.PMR_TEXT_IDS,
N.SHORT_DESCRIPTION,
N.CREATE_USER,
N.CREATE_DATETIME,
N.UPDATE_USER,
N.UPDATE_DATETIME,
N.CONTACT_ID,
N.CUST_NAME,
N.SRC_SUPPORT_ID,
N.CALLER_TYPE_DESCRIPTION,
N.CALLER_STAT_DESCRIPTION,
N.STC_QUES_TXT,
N.FIRST_NAME,
N.LAST_NAME,
N.EMAIL_ADR,
N.IBM_CUST_NUM,
N.ENCRYPT_STRING,
N.PSTC_EMAIL_ADR,
N.NOMINATION_CONTACT_ID,
N.SUBJECTLINE,
N.SRC_NODE,
N.SRC_TRAN_ID,
N.BP_FIRST_NAME,
N.BP_LAST_NAME,
N.BP_CITY,
N.BP_COMPANY_NAME,
'I'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_IA_USER_AUTH_LOG AFTER  INSERT  ON XSR.USER_AUTH  REFERENCING
 NEW AS N  FOR EACH ROW  MODE DB2SQL INSERT INTO XSR.USER_AUTH_LOG
(
USER_ID,
RIGHT_MASK,
IS_LOCKED,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
N.USER_ID,
N.RIGHT_MASK,
N.IS_LOCKED,
N.CREATE_USER,
N.CREATE_DATETIME,
N.UPDATE_USER,
N.UPDATE_DATETIME,
'I'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_ar_kw
before insert on xsr.pmr_adv_route_keyword
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_ar_kwl
before insert on xsr.pmr_adv_route_keyword_list
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_cgcx
before insert on xsr.comp_group_comp_xref
referencing new as n for each row mode db2sql
begin atomic
   set n.create_datetime = current timestamp;--
   set n.update_datetime = current timestamp;--
   if (n.create_user is null or rtrim(n.create_user) = '') then
      set n.create_user = user;--
      set n.update_user = user;--
   end if;--
end;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_IB_MSG
   NO CASCADE BEFORE  INSERT  ON XSR.MSG_OUTBOUND
   REFERENCING  NEW AS N  FOR EACH ROW  MODE DB2SQL
BEGIN ATOMIC
SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
SET N.UPDATE_USER = N.CREATE_USER;--
IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
SET N.CREATE_USER = USER;--
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_aar
before insert on xsr.pmr_a_adv_route
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_aar_ed
before insert on xsr.pmr_a_adv_route_excl_days
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_aar_kw
before insert on xsr.pmr_a_adv_route_keyword
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_aar_kwl
before insert on xsr.pmr_a_adv_route_keyword_list
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_aar_rs
before insert on xsr.pmr_a_adv_route_set
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_aar_ts
before insert on xsr.pmr_a_adv_route_time_slot
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_ar
before insert on xsr.pmr_adv_route
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.update_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_ars
before insert on xsr.pmr_adv_route_set
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.update_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_ar_ed
before insert on xsr.pmr_adv_route_excl_days
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_ar_ts
before insert on xsr.pmr_adv_route_time_slot
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger XSR.t_ib_PMR_BASIC_RTE
before insert on XSR.PMR_BASIC_ROUTE
referencing new as n for each row mode db2sql
begin atomic
   set n.create_datetime = current timestamp;  --
   set n.update_datetime = current timestamp;  --
   set n.update_user = n.create_user;  --
   if (n.create_user is null or rtrim(n.create_user) = '') then
      set n.create_user = user;  --
      set n.update_user = user;  --
   end if;  --
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_IB_PMR_CNTRY_CFG
   NO CASCADE BEFORE INSERT ON XSR.PMR_COUNTRY_CONFIG
   REFERENCING  NEW AS n
   FOR EACH ROW MODE DB2SQL
begin atomic
   set n.create_datetime = current timestamp;--
   set n.update_datetime = current timestamp;--
   set n.update_user = n.create_user;--
   if (n.create_user is null or rtrim(n.create_user) = '') then
      set n.create_user = user;--
      set n.update_user = user;--
   end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_IB_PMR_CNT_O_CFG
   NO CASCADE BEFORE INSERT ON XSR.PMR_COUNTRY_ORG_CONFIG
   REFERENCING  NEW AS n
   FOR EACH ROW MODE DB2SQL
begin atomic
   set n.create_datetime = current timestamp;--
   set n.update_datetime = current timestamp;--
   set n.update_user = n.create_user;--
   if (n.create_user is null or rtrim(n.create_user) = '') then
      set n.create_user = user;--
      set n.update_user = user;--
   end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_cr
before insert on xsr.pmr_country_route
referencing new as n for each row mode db2sql
begin atomic
   set n.create_datetime = current timestamp;--
   set n.update_datetime = current timestamp;--
   if (n.create_user is null or rtrim(n.create_user) = '') then

      set n.create_user = user;--
      set n.update_user = user;--
   end if;--
end;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_excr
before insert on xsr.pmr_ent_exc_route
referencing new as n for each row mode db2sql
begin atomic
   set n.create_datetime = current timestamp;--
   set n.update_datetime = current timestamp;--
   if (n.create_user is null or rtrim(n.create_user) = '') then

      set n.create_user = user;--
      set n.update_user = user;--
   end if;--
end;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_pr
before insert on xsr.pmr_prem_route
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_prs
before insert on xsr.pmr_prem_route_set
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_pr_ed
before insert on xsr.pmr_prem_route_excl_days
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_pr_ts
before insert on xsr.pmr_prem_route_time_slot
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "JBLACKER";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","JBLACKER";
create trigger xsr.t_ib_pmr_sync
before insert on xsr.pmr_sync
referencing new as n for each row mode db2sql
begin atomic
   set n.create_datetime = current timestamp;--
   set n.update_datetime = current timestamp;--
   if (n.create_user is null or rtrim(n.create_user) = '') then

      set n.create_user = user;--
      set n.update_user = user;--
   end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_tar
before insert on xsr.pmr_t_adv_route
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_tars
before insert on xsr.pmr_t_adv_route_set
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_tar_ed
before insert on xsr.pmr_t_adv_route_excl_days
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_tar_kw
before insert on xsr.pmr_t_adv_route_keyword
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_pmr_tar_kwl
before insert on xsr.pmr_t_adv_route_keyword_list
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ib_tar_ts
before insert on xsr.pmr_t_adv_route_time_slot
referencing new as n for each row mode db2sql
begin atomic
set n.create_datetime = current timestamp;--
set n.update_datetime = current timestamp;--
if (n.create_user is null or rtrim(n.create_user) = '') then


set n.create_user = user;--
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_UA_MSG_LOG
   AFTER  UPDATE  ON XSR.MSG_OUTBOUND
   REFERENCING  OLD AS O  NEW AS N  FOR EACH ROW  MODE DB2SQL
INSERT INTO XSR.MSG_LOG
(
  TRAN_ID,
  MSG_TMPL_ID,
  LOCALE,
  SRC_APPL,
  TO,
  FROM,
  CC,
  BCC,
  SUBJECT,
  REASON,
  PMR_NUM,
  BRANCH ,
  RETAIN_CNTRY_CODE,
  PMR_TEXT_IDS,
  SHORT_DESCRIPTION,
  CREATE_USER,
  CREATE_DATETIME,
  UPDATE_USER,
  UPDATE_DATETIME,
  CONTACT_ID,
  CUST_NAME,
  SRC_SUPPORT_ID,
  CALLER_TYPE_DESCRIPTION,
  CALLER_STAT_DESCRIPTION,
  STC_QUES_TXT,
  FIRST_NAME,
  LAST_NAME,
  EMAIL_ADR,
  IBM_CUST_NUM,
  ENCRYPT_STRING,
  PSTC_EMAIL_ADR,
  NOMINATION_CONTACT_ID,
  SUBJECTLINE,
  SRC_NODE,
  SRC_TRAN_ID,
  BP_FIRST_NAME,
  BP_LAST_NAME,
  BP_CITY,
  BP_COMPANY_NAME,
  ACTION_FLAG
)
VALUES
(
N.TRAN_ID,
N.MSG_TMPL_ID,
N.LOCALE,
N.SRC_APPL,
N.TO,
N.FROM,
N.CC,
N.BCC,
N.SUBJECT,
N.REASON,
N.PMR_NUM,
N.BRANCH ,
N.RETAIN_CNTRY_CODE,
N.PMR_TEXT_IDS,
N.SHORT_DESCRIPTION,
O.CREATE_USER,
O.CREATE_DATETIME,
N.UPDATE_USER,
N.UPDATE_DATETIME,
N.CONTACT_ID,
N.CUST_NAME,
N.SRC_SUPPORT_ID,
N.CALLER_TYPE_DESCRIPTION,
N.CALLER_STAT_DESCRIPTION,
N.STC_QUES_TXT,
N.FIRST_NAME,
N.LAST_NAME,
N.EMAIL_ADR,
N.IBM_CUST_NUM,
N.ENCRYPT_STRING,
N.PSTC_EMAIL_ADR,
N.NOMINATION_CONTACT_ID,
N.SUBJECTLINE,
N.SRC_NODE,
N.SRC_TRAN_ID,
N.BP_FIRST_NAME,
N.BP_LAST_NAME,
N.BP_CITY,
N.BP_COMPANY_NAME,
'U'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_UA_USER_AUTH_LOG AFTER  UPDATE  ON XSR.USER_AUTH  REFERENCING
 OLD AS O  NEW AS N  FOR EACH ROW  MODE DB2SQL INSERT INTO XSR.USER_AUTH_LOG
(
USER_ID,
RIGHT_MASK,
IS_LOCKED,
CREATE_USER,
CREATE_DATETIME,
UPDATE_USER,
UPDATE_DATETIME,
ACTION_FLAG
)
VALUES
(
N.USER_ID,
N.RIGHT_MASK,
N.IS_LOCKED,
O.CREATE_USER,
O.CREATE_DATETIME,
N.UPDATE_USER,
N.UPDATE_DATETIME,
'U'
)
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_ar_kw no cascade
before update on xsr.pmr_adv_route_keyword
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_ar_kwl no cascade
before update on xsr.pmr_adv_route_keyword_list
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_cgcx no cascade
before update on xsr.comp_group_comp_xref
referencing new as n for each row mode db2sql
begin atomic
   set n.update_datetime = current timestamp;--
   if (n.update_user is null or rtrim(n.update_user) = '') then
     set n.update_user = user;--
   end if;--
end;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_UB_MSG
   NO CASCADE BEFORE  UPDATE  ON XSR.MSG_OUTBOUND
   REFERENCING  OLD AS O  NEW AS N
   FOR EACH ROW  MODE DB2SQL
BEGIN ATOMIC
SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
IF (N.UPDATE_USER IS NULL OR RTRIM(N.UPDATE_USER) = '') THEN
SET N.UPDATE_USER = USER;--
END IF;--
END
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_aar no cascade
before update on xsr.pmr_a_adv_route
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_aar_ed no cascade
before update on xsr.pmr_a_adv_route_excl_days
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_aar_kw no cascade
before update on xsr.pmr_a_adv_route_keyword
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_aar_kwl no cascade
before update on xsr.pmr_a_adv_route_keyword_list
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_aar_rs no cascade
before update on xsr.pmr_a_adv_route_set
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_aar_ts no cascade
before update on xsr.pmr_a_adv_route_time_slot
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_ar no cascade
before update on xsr.pmr_adv_route
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_ars no cascade
before update on xsr.pmr_adv_route_set
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_ar_ed no cascade
before update on xsr.pmr_adv_route_excl_days
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_ar_ts no cascade
before update on xsr.pmr_adv_route_time_slot
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger XSR.t_ub_PMR_BASIC_RTE no cascade
before update on XSR.PMR_BASIC_ROUTE
referencing new as n for each row mode db2sql
begin atomic
   set n.update_datetime = current timestamp;  --
   if (n.update_user is null or rtrim(n.update_user) = '') then
     set n.update_user = user;  --
   end if;  --
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_UB_PMR_CNTRY_CFG
   NO CASCADE BEFORE UPDATE ON XSR.PMR_COUNTRY_CONFIG
   REFERENCING  NEW AS n
   FOR EACH ROW MODE DB2SQL
begin atomic
   set n.update_datetime = current timestamp;--
   if (n.update_user is null or rtrim(n.update_user) = '') then
     set n.update_user = user;--
   end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
CREATE TRIGGER XSR.T_UB_PMR_CNT_O_CFG
   NO CASCADE BEFORE UPDATE ON XSR.PMR_COUNTRY_ORG_CONFIG
   REFERENCING  NEW AS n
   FOR EACH ROW MODE DB2SQL
begin atomic
   set n.update_datetime = current timestamp;--
   if (n.update_user is null or rtrim(n.update_user) = '') then
     set n.update_user = user;--
   end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_cr no cascade
before update on xsr.pmr_country_route
referencing new as n for each row mode db2sql
begin atomic
   set n.update_datetime = current timestamp;--
   if (n.update_user is null or rtrim(n.update_user) = '') then
     set n.update_user = user;--
   end if;--
end;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_excr no cascade
before update on xsr.pmr_ent_exc_route
referencing new as n for each row mode db2sql
begin atomic
   set n.update_datetime = current timestamp;--
   if (n.update_user is null or rtrim(n.update_user) = '') then
     set n.update_user = user;--
   end if;--
end;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_pr no cascade
before update on xsr.pmr_prem_route
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_prs no cascade
before update on xsr.pmr_prem_route_set
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_pr_ed no cascade
before update on xsr.pmr_prem_route_excl_days
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_pr_ts no cascade
before update on xsr.pmr_prem_route_time_slot
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "JBLACKER";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","JBLACKER";
create trigger xsr.t_ub_pmr_sync no cascade
before update on xsr.pmr_sync
referencing new as n for each row mode db2sql
begin atomic
   set n.update_datetime = current timestamp;--
   if (n.update_user is null or rtrim(n.update_user) = '') then
     set n.update_user = user;--
   end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_tar no cascade
before update on xsr.pmr_t_adv_route
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_tars no cascade
before update on xsr.pmr_t_adv_route_set
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_tar_ed no cascade
before update on xsr.pmr_t_adv_route_excl_days
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_tar_kw no cascade
before update on xsr.pmr_t_adv_route_keyword
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_tar_kwl no cascade
before update on xsr.pmr_t_adv_route_keyword_list
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;

SET CURRENT SCHEMA = "XSRDBADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","XSRDBADM";
create trigger xsr.t_ub_pmr_tar_ts no cascade
before update on xsr.pmr_t_adv_route_time_slot
referencing new as n for each row mode db2sql
begin atomic
set n.update_datetime = current timestamp;--
if (n.update_user is null or rtrim(n.update_user) = '') then
set n.update_user = user;--
end if;--
end
;



COMMIT WORK;



