

-- DDL Statements for foreign keys on Table "XSR     "."FAMS"

ALTER TABLE "XSR     "."FAMS" 
	ADD CONSTRAINT "FAMS_FK1" FOREIGN KEY
		("MESSAGE_ID")
	REFERENCES "XSR     "."FAMS_MESSAGE"
		("MESSAGE_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."FAMS" 
	ADD CONSTRAINT "FAMS_FK2" FOREIGN KEY
		("STORAGE_NODE_ID")
	REFERENCES "XSR     "."FAMS_NODE_INFO"
		("NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."FAMS_APP_INFO"

ALTER TABLE "XSR     "."FAMS_APP_INFO" 
	ADD CONSTRAINT "FAMS_APP_INFO_FK1" FOREIGN KEY
		("DUMP_NODE_ID")
	REFERENCES "XSR     "."FAMS_NODE_INFO"
		("NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."FAMS_CONFIG"

ALTER TABLE "XSR     "."FAMS_CONFIG" 
	ADD CONSTRAINT "FAMS_CONFIG_FK1" FOREIGN KEY
		("DEFAULT_DUMP_NODE_ID")
	REFERENCES "XSR     "."FAMS_NODE_INFO"
		("NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."FAMS_CONFIG" 
	ADD CONSTRAINT "FAMS_CONFIG_FK2" FOREIGN KEY
		("DEFAULT_STORAGE_NODE_ID")
	REFERENCES "XSR     "."FAMS_NODE_INFO"
		("NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."FAMS_CONFIG" 
	ADD CONSTRAINT "FAMS_CONFIG_FK3" FOREIGN KEY
		("SCAN_NODE_ID")
	REFERENCES "XSR     "."FAMS_NODE_INFO"
		("NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."MSG_TOKEN"

ALTER TABLE "XSR     "."MSG_TOKEN" 
	ADD CONSTRAINT "MSG_TOKEN_FK1" FOREIGN KEY
		("MSG_TMPL_ID",
		 "LOCALE")
	REFERENCES "XSR     "."MSG_TMPL"
		("MSG_TMPL_ID",
		 "LOCALE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."COMP_GROUP"

ALTER TABLE "XSR     "."COMP_GROUP" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(STATUS in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."COMP_GROUP_COMP_XREF"

ALTER TABLE "XSR     "."COMP_GROUP_COMP_XREF" 
	ADD CONSTRAINT "CMP_GRP_CMP_FK01" FOREIGN KEY
		("COMP_GROUP_ID")
	REFERENCES "XSR     "."COMP_GROUP"
		("COMP_GROUP_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ROUTE_LOG"

ALTER TABLE "XSR     "."PMR_ROUTE_LOG" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(CREATE_FLAG in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."AUDIT_LOG"

ALTER TABLE "XSR     "."AUDIT_LOG" 
	ADD CONSTRAINT "AUDIT_LOG_FK1" FOREIGN KEY
		("APP_ID")
	REFERENCES "XSR     "."APP_TYPE"
		("APP_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."AUDIT_LOG" 
	ADD CONSTRAINT "AUDIT_LOG_FK2" FOREIGN KEY
		("SRC_APP_ID")
	REFERENCES "XSR     "."APP_TYPE"
		("APP_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."AUDIT_LOG" 
	ADD CONSTRAINT "AUDIT_LOG_FK3" FOREIGN KEY
		("ACTION_ID")
	REFERENCES "XSR     "."AUDIT_ACTION_TYPE"
		("ACTION_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."AUDIT_LOG" 
	ADD CONSTRAINT "AUDIT_LOG_FK4" FOREIGN KEY
		("OBJ_TYPE_ID")
	REFERENCES "XSR     "."AUDIT_OBJ_TYPE"
		("OBJ_TYPE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."NOTIFY_EVENT_TRAN"

ALTER TABLE "XSR     "."NOTIFY_EVENT_TRAN" 
	ADD CONSTRAINT "NTF_EVENT_TRAN_FK1" FOREIGN KEY
		("EVENT_TYPE_ID")
	REFERENCES "XSR     "."NOTIFY_EVENT_TYPE"
		("EVENT_TYPE_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."NOTIFY_EVENT_TYPE_ACTION_XREF"

ALTER TABLE "XSR     "."NOTIFY_EVENT_TYPE_ACTION_XREF" 
	ADD CONSTRAINT "NTF_EVENT_TAX_FK" FOREIGN KEY
		("EVENT_TYPE_ID")
	REFERENCES "XSR     "."NOTIFY_EVENT_TYPE"
		("EVENT_TYPE_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."NOTIFY_EVENT_TYPE_ACTION_XREF" 
	ADD CONSTRAINT "NTF_EVENT_TAX_FK2" FOREIGN KEY
		("ACTION_TYPE_ID")
	REFERENCES "XSR     "."NOTIFY_EVENT_ACTION_TYPE"
		("ACTION_TYPE_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."NOTIFY_EVENT_USER_TRAN"

ALTER TABLE "XSR     "."NOTIFY_EVENT_USER_TRAN" 
	ADD CONSTRAINT "NTF_EVENT_UT_FK1" FOREIGN KEY
		("EVENT_ID")
	REFERENCES "XSR     "."NOTIFY_EVENT_TRAN"
		("EVENT_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."NOTIFY_EVENT_USER_TRAN" 
	ADD CONSTRAINT "NTF_EVENT_UT_FK2" FOREIGN KEY
		("EVENT_REG_ID")
	REFERENCES "XSR     "."NOTIFY_EVENT_REGISTRATION"
		("EVENT_REG_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."USER_LOGIN_ERR_LOG"

ALTER TABLE "XSR     "."USER_LOGIN_ERR_LOG" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(INACT_FLAG = 0 OR INACT_FLAG = 1)
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_ADV_ROUTE"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_ADV_RTE_FK01" FOREIGN KEY
		("OS_ID")
	REFERENCES "XSR     "."AVL_OPERATING_SYSTEM"
		("OS_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_ADV_RTE_FK02" FOREIGN KEY
		("ROUTE_TIME_SLOT_ID")
	REFERENCES "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"
		("ROUTE_TIME_SLOT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_ADV_RTE_FK03" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_ADV_RTE_FK04" FOREIGN KEY
		("ROUTE_KEYWORD_LIST_ID")
	REFERENCES "XSR     "."PMR_ADV_ROUTE_KEYWORD_LIST"
		("ROUTE_KEYWORD_LIST_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(CREATE_FLAG in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_ADV_RTE_CK" CHECK 
		(CREATE_FLAG=1 OR CREATE_FLAG=0)
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_ADV_ROUTE_SET"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_SET" 
	ADD CONSTRAINT "PAR_S_FK02" FOREIGN KEY
		("COMP_GROUP_ID")
	REFERENCES "XSR     "."COMP_GROUP"
		("COMP_GROUP_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "PAR_TIME_SLOT_FK1" FOREIGN KEY
		("TIME_ZONE_ID")
	REFERENCES "XSR     "."TIME_ZONE"
		("TIME_ZONE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "PAR_TIME_SLOT_FK2" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_1" CHECK 
		(MON in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_2" CHECK 
		(TUE in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_3" CHECK 
		(WED in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_4" CHECK 
		(THU in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_5" CHECK 
		(FRI in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_6" CHECK 
		(SAT in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_7" CHECK 
		(SUN in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_ADV_ROUTE_EXCL_DAYS"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_EXCL_DAYS" 
	ADD CONSTRAINT "PMR_AR_ED_FK01" FOREIGN KEY
		("ROUTE_TIME_SLOT_ID")
	REFERENCES "XSR     "."PMR_ADV_ROUTE_TIME_SLOT"
		("ROUTE_TIME_SLOT_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_ADV_ROUTE_EXCL_DAYS"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_EXCL_DAYS" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(REPEAT_YEARLY in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_ADV_ROUTE_KEYWORD"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_KEYWORD" 
	ADD CONSTRAINT "PAR_KW_FK01" FOREIGN KEY
		("ROUTE_KEYWORD_LIST_ID")
	REFERENCES "XSR     "."PMR_ADV_ROUTE_KEYWORD_LIST"
		("ROUTE_KEYWORD_LIST_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_ADV_ROUTE_KEYWORD_LIST"

ALTER TABLE "XSR     "."PMR_ADV_ROUTE_KEYWORD_LIST" 
	ADD CONSTRAINT "PMR_AR_KL_FK01" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_T_ADV_ROUTE"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_T_ADV_RTE_FK01" FOREIGN KEY
		("OS_ID")
	REFERENCES "XSR     "."AVL_OPERATING_SYSTEM"
		("OS_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_T_ADV_RTE_FK03" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_T_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_T_ADV_RTE_FK04" FOREIGN KEY
		("ROUTE_TIME_SLOT_ID")
	REFERENCES "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"
		("ROUTE_TIME_SLOT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_T_ADV_RTE_FK05" FOREIGN KEY
		("ROUTE_KEYWORD_LIST_ID")
	REFERENCES "XSR     "."PMR_T_ADV_ROUTE_KEYWORD_LIST"
		("ROUTE_KEYWORD_LIST_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(CREATE_FLAG in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_T_ADV_ROUTE_SET"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_SET" 
	ADD CONSTRAINT "PTAR_S_FK02" FOREIGN KEY
		("COMP_GROUP_ID")
	REFERENCES "XSR     "."COMP_GROUP"
		("COMP_GROUP_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "PTAR_TIME_SLOT_FK1" FOREIGN KEY
		("TIME_ZONE_ID")
	REFERENCES "XSR     "."TIME_ZONE"
		("TIME_ZONE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "PTAR_TIME_SLOT_FK2" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_T_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_1" CHECK 
		(MON in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_2" CHECK 
		(TUE in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_3" CHECK 
		(WED in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_4" CHECK 
		(THU in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_5" CHECK 
		(FRI in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_6" CHECK 
		(SAT in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_7" CHECK 
		(SUN in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_T_ADV_ROUTE_KEYWORD_LIST"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_KEYWORD_LIST" 
	ADD CONSTRAINT "PMR_T_AR_KL_FK01" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_T_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_T_ADV_ROUTE_KEYWORD"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_KEYWORD" 
	ADD CONSTRAINT "PTAR_KW_FK02" FOREIGN KEY
		("ROUTE_KEYWORD_LIST_ID")
	REFERENCES "XSR     "."PMR_T_ADV_ROUTE_KEYWORD_LIST"
		("ROUTE_KEYWORD_LIST_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_T_ADV_ROUTE_EXCL_DAYS"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_EXCL_DAYS" 
	ADD CONSTRAINT "PMR_T_AR_ED_FK01" FOREIGN KEY
		("ROUTE_TIME_SLOT_ID")
	REFERENCES "XSR     "."PMR_T_ADV_ROUTE_TIME_SLOT"
		("ROUTE_TIME_SLOT_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_T_ADV_ROUTE_EXCL_DAYS"

ALTER TABLE "XSR     "."PMR_T_ADV_ROUTE_EXCL_DAYS" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(REPEAT_YEARLY in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_A_ADV_ROUTE"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_A_ADV_RTE_FK01" FOREIGN KEY
		("OS_ID")
	REFERENCES "XSR     "."AVL_OPERATING_SYSTEM"
		("OS_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_A_ADV_RTE_FK03" FOREIGN KEY
		("ROUTE_TIME_SLOT_ID")
	REFERENCES "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"
		("ROUTE_TIME_SLOT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_A_ADV_RTE_FK04" FOREIGN KEY
		("ROUTE_KEYWORD_LIST_ID")
	REFERENCES "XSR     "."PMR_A_ADV_ROUTE_KEYWORD_LIST"
		("ROUTE_KEYWORD_LIST_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE" 
	ADD CONSTRAINT "PMR_A_ADV_RTE_FK05" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_A_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(CREATE_FLAG in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_A_ADV_ROUTE_SET"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_SET" 
	ADD CONSTRAINT "PAAR_S_FK02" FOREIGN KEY
		("COMP_GROUP_ID")
	REFERENCES "XSR     "."COMP_GROUP"
		("COMP_GROUP_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_A_ADV_ROUTE_KEYWORD_LIST"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_KEYWORD_LIST" 
	ADD CONSTRAINT "PMR_T_AR_KL_FK01" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_A_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_A_ADV_ROUTE_KEYWORD"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_KEYWORD" 
	ADD CONSTRAINT "PAAR_KW_LIST_FK02" FOREIGN KEY
		("ROUTE_KEYWORD_LIST_ID")
	REFERENCES "XSR     "."PMR_A_ADV_ROUTE_KEYWORD_LIST"
		("ROUTE_KEYWORD_LIST_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "PAAR_TIME_SLOT_FK1" FOREIGN KEY
		("TIME_ZONE_ID")
	REFERENCES "XSR     "."TIME_ZONE"
		("TIME_ZONE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "PTAR_TIME_SLOT_FK2" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_A_ADV_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_1" CHECK 
		(MON in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_2" CHECK 
		(TUE in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_3" CHECK 
		(WED in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_4" CHECK 
		(THU in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_5" CHECK 
		(FRI in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_6" CHECK 
		(SAT in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_7" CHECK 
		(SUN in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_A_ADV_ROUTE_EXCL_DAYS"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_EXCL_DAYS" 
	ADD CONSTRAINT "PMR_A_AR_ED_FK01" FOREIGN KEY
		("ROUTE_TIME_SLOT_ID")
	REFERENCES "XSR     "."PMR_A_ADV_ROUTE_TIME_SLOT"
		("ROUTE_TIME_SLOT_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_A_ADV_ROUTE_EXCL_DAYS"

ALTER TABLE "XSR     "."PMR_A_ADV_ROUTE_EXCL_DAYS" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(REPEAT_YEARLY in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_PREM_ROUTE"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE" 
	ADD CONSTRAINT "PMR_PREM_RTE_FK01" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_PREM_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_PREM_ROUTE" 
	ADD CONSTRAINT "PMR_PREM_RTE_FK02" FOREIGN KEY
		("ROUTE_TIME_SLOT_ID")
	REFERENCES "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"
		("ROUTE_TIME_SLOT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "PPR_TIME_SLOT_FK1" FOREIGN KEY
		("TIME_ZONE_ID")
	REFERENCES "XSR     "."TIME_ZONE"
		("TIME_ZONE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "PPR_TIME_SLOT_FK2" FOREIGN KEY
		("ROUTE_SET_ID")
	REFERENCES "XSR     "."PMR_PREM_ROUTE_SET"
		("ROUTE_SET_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_1" CHECK 
		(MON in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_2" CHECK 
		(TUE in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_3" CHECK 
		(WED in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_4" CHECK 
		(THU in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_5" CHECK 
		(FRI in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_6" CHECK 
		(SAT in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_TIME_SLOT" 
	ADD CONSTRAINT "BOOL_CHECK_7" CHECK 
		(SUN in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_PREM_ROUTE_EXCL_DAYS"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_EXCL_DAYS" 
	ADD CONSTRAINT "PMR_PR_ED_FK1" FOREIGN KEY
		("ROUTE_TIME_SLOT_ID")
	REFERENCES "XSR     "."PMR_PREM_ROUTE_TIME_SLOT"
		("ROUTE_TIME_SLOT_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "XSR     "."PMR_PREM_ROUTE_EXCL_DAYS"

ALTER TABLE "XSR     "."PMR_PREM_ROUTE_EXCL_DAYS" 
	ADD CONSTRAINT "BOOL_CHECK" CHECK 
		(REPEAT_YEARLY in (0, 1))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_ENT_EXC_ROUTE"

ALTER TABLE "XSR     "."PMR_ENT_EXC_ROUTE" 
	ADD CONSTRAINT "PMR_ENT_EXC_FK01" FOREIGN KEY
		("COMP_GROUP_ID")
	REFERENCES "XSR     "."COMP_GROUP"
		("COMP_GROUP_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."USER_PROD_FAVORITES"

ALTER TABLE "XSR     "."USER_PROD_FAVORITES" 
	ADD CONSTRAINT "USR_PROD_FAV_FK1" FOREIGN KEY
		("USER_ID")
	REFERENCES "XSR     "."USER_PROFILE"
		("USER_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_RETRY_TEXT"

ALTER TABLE "XSR     "."PMR_RETRY_TEXT" 
	ADD CONSTRAINT "PMR_RETRY_TEXT_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_RETRY"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."USER_PMR_RETRY_XREF"

ALTER TABLE "XSR     "."USER_PMR_RETRY_XREF" 
	ADD CONSTRAINT "USR_PMR_RTY_X_FK2" FOREIGN KEY
		("USER_ID")
	REFERENCES "XSR     "."USER_PROFILE"
		("USER_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."USER_PMR_RETRY_XREF" 
	ADD CONSTRAINT "USR_PMR_RTY_X_FK3" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_RETRY"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."USER_PMR_DRAFT_XREF"

ALTER TABLE "XSR     "."USER_PMR_DRAFT_XREF" 
	ADD CONSTRAINT "USR_PMR_DRFT_X_FK3" FOREIGN KEY
		("USER_ID")
	REFERENCES "XSR     "."USER_PROFILE"
		("USER_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."USER_PMR_DRAFT_XREF" 
	ADD CONSTRAINT "USR_PMR_DRFT_X_FK4" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_DRAFT"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_SIG_LINES"

ALTER TABLE "XSR     "."PMR_SIG_LINES" 
	ADD CONSTRAINT "PMR_SIG_LN_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_HEADER"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."USER_PMR_XREF"

ALTER TABLE "XSR     "."USER_PMR_XREF" 
	ADD CONSTRAINT "USR_PMR_XREF_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_HEADER"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."USER_PMR_XREF" 
	ADD CONSTRAINT "USR_PMR_XREF_FK2" FOREIGN KEY
		("USER_ID")
	REFERENCES "XSR     "."USER_PROFILE"
		("USER_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_TEXT"

ALTER TABLE "XSR     "."PMR_TEXT" 
	ADD CONSTRAINT "PMR_TEXT_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_HEADER"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."APPL_AUTH"	
ALTER TABLE xsr.appl_auth ADD CONSTRAINT appl_auth_fk1 FOREIGN KEY (admin_rights_id) 
    REFERENCES xsr.admin_rights (admin_rights_id) 
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
    ENFORCED
    ENABLE QUERY OPTIMIZATION;	

-- DDL Statements for foreign keys on Table "XSR     "."ADMIN_AUTH"

ALTER TABLE "XSR     "."ADMIN_AUTH" 
	ADD CONSTRAINT "ADMIN_AUTH_FK1" FOREIGN KEY
		("ADMIN_RIGHTS_ID")
	REFERENCES "XSR     "."ADMIN_RIGHTS"
		("ADMIN_RIGHTS_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."ADMIN_RIGHTS"

ALTER TABLE "XSR     "."ADMIN_RIGHTS" 
	ADD CONSTRAINT "ADMIN_RIGHTS_FK1" FOREIGN KEY
		("APP_ID")
	REFERENCES "XSR     "."APP_TYPE"
		("APP_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_COUNTRY_ORG_CONFIG"

ALTER TABLE "XSR     "."PMR_COUNTRY_ORG_CONFIG" 
	ADD CONSTRAINT "PMR_CTRYORGCFG_FK1" FOREIGN KEY
		("ISO_CNTRY_CODE_2")
	REFERENCES "XSR     "."PMR_COUNTRY_CONFIG"
		("ISO_CNTRY_CODE_2")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."BP_SITE_PMR_XREF"

ALTER TABLE "XSR     "."BP_SITE_PMR_XREF" 
	ADD CONSTRAINT "BP_PMR_XREF_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_HEADER"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."BP_SITE_PMR_RETRY_XREF"

ALTER TABLE "XSR     "."BP_SITE_PMR_RETRY_XREF" 
	ADD CONSTRAINT "BP_PMR_RETRY_X_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_RETRY"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_RETAIN_INFO"

ALTER TABLE "XSR     "."PMR_RETAIN_INFO" 
	ADD CONSTRAINT "PMR_HEADER_RI_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_HEADER"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_RETAIN_INFO" 
	ADD CONSTRAINT "REQST_TYPE_FK1" FOREIGN KEY
		("REQUEST_TYPE_ID")
	REFERENCES "XSR     "."AVL_REQUEST_TYPE"
		("AVL_REQUEST_TYPE_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_RETRY_RETAIN_INFO"

ALTER TABLE "XSR     "."PMR_RETRY_RETAIN_INFO" 
	ADD CONSTRAINT "PMR_RETRY_RI_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_RETRY"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_RETRY_RETAIN_INFO" 
	ADD CONSTRAINT "REQST_TYPE_FK3" FOREIGN KEY
		("REQUEST_TYPE_ID")
	REFERENCES "XSR     "."AVL_REQUEST_TYPE"
		("AVL_REQUEST_TYPE_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."BP_SITE_PMR_DRAFT_XREF"

ALTER TABLE "XSR     "."BP_SITE_PMR_DRAFT_XREF" 
	ADD CONSTRAINT "BP_PMR_DRAFT_X_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_DRAFT"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_DRAFT_RETAIN_INFO"

ALTER TABLE "XSR     "."PMR_DRAFT_RETAIN_INFO" 
	ADD CONSTRAINT "PMR_DRAFT_RI_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_DRAFT"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "XSR     "."PMR_DRAFT_RETAIN_INFO" 
	ADD CONSTRAINT "REQST_TYPE_FK2" FOREIGN KEY
		("REQUEST_TYPE_ID")
	REFERENCES "XSR     "."AVL_REQUEST_TYPE"
		("AVL_REQUEST_TYPE_ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_DRAFT_XSR_INFO"

ALTER TABLE "XSR     "."PMR_DRAFT_XSR_INFO" 
	ADD CONSTRAINT "PMR_DRAFT_XI_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_DRAFT"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_XSR_INFO"

ALTER TABLE "XSR     "."PMR_XSR_INFO" 
	ADD CONSTRAINT "PMR_HEADER_XI_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_HEADER"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "XSR     "."PMR_RETRY_XSR_INFO"

ALTER TABLE "XSR     "."PMR_RETRY_XSR_INFO" 
	ADD CONSTRAINT "PMR_RETRY_XI_FK1" FOREIGN KEY
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	REFERENCES "XSR     "."PMR_RETRY"
		("SRC_TRAN_ID",
		 "SRC_APPL",
		 "SRC_NODE")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;



COMMIT WORK;

